{
 "title": "Kubernetes / Views / Global",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": "n150" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "job",
    "query": {
     "query": "label_values(node_cpu_seconds_total{},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=~\".*\"}[$__rate_interval])))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) / sum(machine_cpu_cores{})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) / sum(machine_cpu_cores{})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\".*\"} - node_memory_MemAvailable_bytes{job=~\".*\"}) / sum(node_memory_MemTotal_bytes{job=~\".*\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) / sum(machine_memory_bytes{})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\"} == 1)) / sum(machine_memory_bytes{})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{}))"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(kube_namespace_labels{})", "legendFormat": "Namespaces" },
    {
     "expr": "sum(kube_pod_container_status_running{})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running Pods"
    },
    { "expr": "sum(kube_service_info{})", "legendFormat": "Services" },
    { "expr": "sum(kube_endpoint_info{})", "legendFormat": "Endpoints" },
    { "expr": "sum(kube_ingress_info{})", "legendFormat": "Ingresses" },
    { "expr": "sum(kube_deployment_labels{})", "legendFormat": "Deployments" },
    { "expr": "sum(kube_statefulset_labels{})", "legendFormat": "Statefulsets" },
    { "expr": "sum(kube_daemonset_labels{})", "legendFormat": "Daemonsets" },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{})",
     "legendFormat": "Persistent Volume Claims"
    },
    { "expr": "sum(kube_hpa_labels{})", "legendFormat": "Horizontal Pod Autoscalers" },
    { "expr": "sum(kube_configmap_info{})", "legendFormat": "Configmaps" },
    { "expr": "sum(kube_secret_info{})", "legendFormat": "Secrets" },
    {
     "expr": "sum(kube_networkpolicy_labels{})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(count by (node) (kube_node_info{}))",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=~\".*\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\"} == 1))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\"} == 1))",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\".*\"} - node_memory_MemAvailable_bytes{job=~\".*\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\"} == 1))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"} and on(namespace, pod) max by (namespace, pod) (kube_pod_status_phase{phase=\"Running\"} == 1))",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=~\".*\"}[$__rate_interval])))",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\".*\"} - node_memory_MemAvailable_bytes{job=~\".*\"}) / sum(node_memory_MemTotal_bytes{job=~\".*\"})",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", job=~\".*\"}[$__rate_interval]))) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=~\".*\"} - node_memory_MemAvailable_bytes{job=~\".*\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\"}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Core Throttled by instance",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total{job=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class{}) by (qos_class)",
     "legendFormat": "{{ qos_class }} pods"
    },
    { "expr": "sum(kube_pod_info{})", "legendFormat": "Total pods" }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{}) by (reason)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "OOM Events by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Container Restarts by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{}[$__rate_interval])) by (namespace) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Global Network Utilization by device",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc).*\", job=~\".*\"}[$__rate_interval])) by (device)",
     "legendFormat": "Received : {{ device }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc).*\", job=~\".*\"}[$__rate_interval])) by (device)",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{job=~\".*\"}[$__rate_interval]))",
     "legendFormat": "Packets dropped (receive)"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{job=~\".*\"}[$__rate_interval]))",
     "legendFormat": "Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{}[$__rate_interval])) by (namespace)",
     "legendFormat": "Received : {{ namespace }}"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{}[$__rate_interval])) by (namespace)",
     "legendFormat": "Transmitted : {{ namespace }}"
    }
   ]
  },
  {
   "title": "Total Network Received (with all virtual devices) by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{job=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (without loopback)  by instance",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|lo).*\", job=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|lo).*\", job=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (loopback only) by instance",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"lo\", job=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{device=\"lo\", job=~\".*\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  }
 ]
}
{
 "title": "Kubernetes / Views / Nodes",
 "description": "This is a modern 'Nodes View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": "n150" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{}, node)"
    }
   },
   { "name": "instance", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=~\"$instance\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"}) / sum(node_memory_MemTotal_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "List of pods on node ($node)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{node=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_time_seconds{instance=~\"$instance\"} - node_boot_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval]) * 100) by (mode)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"} - node_memory_MemFree_bytes{instance=~\"$instance\"} - (node_memory_Cached_bytes{instance=~\"$instance\"} + node_memory_Buffers_bytes{instance=~\"$instance\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$instance\"}",
     "legendFormat": "RAM Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\"} - node_memory_SwapFree_bytes{instance=~\"$instance\"}",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "SWAP Total"
    }
   ]
  },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{node=\"$node\", image!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{node=\"$node\", image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of CPU Core Throttled",
   "type": "timeseries",
   "description": "Number of times a CPU core has been throttled on an instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Nb of cpu core throttles"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Context Switches & Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "rate(node_intr_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=~\"$instance\"}",
     "legendFormat": "Maximum file descriptors"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$instance\"}",
     "legendFormat": "Allocated file descriptors"
    }
   ]
  },
  {
   "title": "Time Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{instance=~\"$instance\"}",
     "legendFormat": "Estimated error in seconds"
    },
    {
     "expr": "node_timex_maxerror_seconds{instance=~\"$instance\"}",
     "legendFormat": "Maximum error in seconds"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Network usage (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_errs_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_errs_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network usage (packet/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_packets_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network total drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_drop_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "TCP Currently Established",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$instance\"}",
     "legendFormat": "TCP Currently Established"
    }
   ]
  },
  {
   "title": "NF Conntrack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{instance=~\"$instance\"}",
     "legendFormat": "NF Conntrack entries"
    },
    {
     "expr": "node_nf_conntrack_entries_limit{instance=~\"$instance\"}",
     "legendFormat": "NF Conntrack limit"
    }
   ]
  },
  { "title": "Kubernetes Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{node=\"$node\"}) by (persistentvolumeclaim, namespace) / max(kubelet_volume_stats_capacity_bytes{node=\"$node\"}) by (persistentvolumeclaim, namespace)",
     "legendFormat": "{{ namespace }} - {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Usage in GB",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{node=\"$node\"}) by (persistentvolumeclaim, namespace)"
    },
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{node=\"$node\"}) by (persistentvolumeclaim, namespace)"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_inodes_used{node=\"$node\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{node=\"$node\"}) by (persistentvolumeclaim) * 100",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "Node Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "FS usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$instance\"} * 100) / node_filesystem_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "FS inode usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_files_free{instance=~\"$instance\"} / node_filesystem_files{instance=~\"$instance\"} * 100)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Reads by disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Writes by disk (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Completed reads by disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "read/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Completed writes by disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "write/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk(s) io/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "io/s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_now{instance=~\"$instance\"}[$__rate_interval]) ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "FS - Device Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(node_filesystem_device_error{instance=~\"$instance\"}) by (mountpoint)",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  }
 ]
}
{
 "title": "Prometheus",
 "description": "This is a modern 'Prometheus' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": "n150" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(prometheus_build_info{}, pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Prometheus version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{pod=~\"$pod\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Instance Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\"} < 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TSDB Head Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Liveness by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Config - Last Successful Reload by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_config_last_reload_successful{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Target Scrapes Errors by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_scrapes_exceeded_body_size_limit_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Exceeded body size limit"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_exceeded_sample_limit_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Exceeded sample limit"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Duplicate timestamp"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_out_of_bounds_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Sample out of bounds"
    },
    {
     "expr": "sum(rate(prometheus_target_scrapes_sample_out_of_order_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Sample out of order"
    }
   ]
  },
  {
   "title": "Number of Targets by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_sd_discovered_targets{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Target Sync by pod, scrape_job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{pod=~\"$pod\"}[$__rate_interval])) by (pod, scrape_job) * 1000",
     "legendFormat": "{{ pod }} - {{ scrape_job }}"
    }
   ]
  },
  {
   "title": "Average Scrape Interval by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "round(sum(rate(prometheus_target_interval_length_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(prometheus_target_interval_length_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Prometheus TSDB / Query Engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TSDB Head Series & Chunks by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }} - Head Series"
    },
    {
     "expr": "sum(prometheus_tsdb_head_chunks{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }} - Head Chunks"
    }
   ]
  },
  {
   "title": "TSDB Head samples appended - rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "TSDB Blocks Loaded by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_blocks_loaded{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }} - Head Series"
    }
   ]
  },
  {
   "title": "TSDB Rate of Compactions by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Total Compactions"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_triggered_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Triggered Compactions"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_skipped_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Skipped Compactions"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_compactions_failed_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Failed Compactions"
    }
   ]
  },
  {
   "title": "TSDB Reload Failures by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_reloads_failures_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "TSDB Created & Deleted series by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_series_created_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Created series"
    },
    {
     "expr": "sum(rate(prometheus_tsdb_head_series_removed_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Deleted series"
    }
   ]
  },
  {
   "title": "Engine Query Count by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_engine_query_duration_seconds_count{pod=~\"$pod\", slice=\"inner_eval\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Engine Query Duration by pod, slice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prometheus_engine_query_duration_seconds{pod=~\"$pod\"}) by (pod, slice) * 1000",
     "legendFormat": "{{ pod }} - {{ slice }}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage by pod, container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod, container)",
     "legendFormat": "{{ pod }} - {{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", image!=\"\", container!=\"\"}) by (pod, container)",
     "legendFormat": "{{ pod }} - {{ container }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Persistent Volumes - Capacity and usage in %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*prom.*\"}) by (persistentvolumeclaim, namespace) / max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*prom.*\"}) by (persistentvolumeclaim, namespace)",
     "legendFormat": "{{ namespace }} - {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Capacity and usage in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\".*prom.*\"}) by (persistentvolumeclaim, namespace)",
     "legendFormat": "{{ namespace }} - {{ persistentvolumeclaim }} - Used"
    },
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*prom.*\"}) by (persistentvolumeclaim, namespace)",
     "legendFormat": "{{ namespace }} - {{ persistentvolumeclaim }} - Capacity"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(kubelet_volume_stats_inodes_used{persistentvolumeclaim=~\".*prom.*\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_inodes{persistentvolumeclaim=~\".*prom.*\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network - Bandwidth by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Transmitted"
    }
   ]
  },
  {
   "title": "Network - Packets Dropped by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_dropped_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_dropped_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Transmitted"
    }
   ]
  },
  {
   "title": "Network - Errors by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_errors_total{pod=~\"$pod\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{ pod }} - Transmitted"
    }
   ]
  }
 ]
}