extensions:
  file_storage/journald:
    directory: /var/lib/otelcol/journald
    create_directory: true

receivers:
  journald:
    directory: /var/log/journal
    start_at: end
    storage: file_storage/journald

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 200
    spike_limit_mib: 50
  resource:
    attributes:
      - key: service.name
        value: systemd-journal
        action: insert
      - key: host.name
        value: n150
        action: upsert
  batch:

exporters:
  otlphttp:
    endpoint: http://127.0.0.1:31318

service:
  extensions: [file_storage/journald]
  pipelines:
    logs:
      receivers: [journald]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp]
