apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - android-usage-receiver.yaml
  - nats-client-auth-sealedsecret.yaml
images:
  - name: ghcr.io/kazu728/android-usage-receiver
    newTag: latest
