---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nats-client-auth
  namespace: default
spec:
  encryptedData:
    token: AgAmgzzxvSeHbEIt0UMsgP1f/g4gHT+SJAP/59k7SweUtKdWSdL0Bq/Lp1p+LngDoQUzl5v5rjbgYbgGSAyqguXAt1C0DL0Tfqzbmmh2j6eBt/bz2M/3FRGBOm9h4LlzsOHGkRMLPi5cyi4p1u7/fDAEVWE7ZQN2WwWC9AMFILqVaDCTyVuVRQPHaDr/FmD9fjpNPTG4pE8ZTM5M2MdX+Gl0E8mvYYfKBaXCbd1XCkEE4/zKozg8MddAzPrkb30ZHiobkLuiDmE1ToSar9jPZODR6tjfJdORr/xq75pMsfKawLfbCVvPwsmU4YorjXaEEST6yTSOuCZrm1bDDFK8N7MgOFw0p2qbWV8ach1pR7bTZpy/dgapAzGt4VT9I8PZ/MKS7E+O8g60OOvBw739wHZfZqZND3qk3bpAHYTuwV9yYVasdhyghFguI0vdNWO91UDneBV25MY47kqat23tWEEqkoS92UTW26JFVkOn4NsvFzwTuLhHFVTkSuqGxPnyhcIKR9LQHPaqsQkPlpcqVpiYi6vjajezx3scVvmOoqrQKt1fDUsVm7rJ3+aDNRYMPcp8J1a7ceTssV9PzWtTzpx8lzxuiA5ash1YuPojFaua5IWHgCWEFpIdLITTLd5vS5Slbx3wqeoEpAQLGUNAyV6jieFwxKe4yFq0/zS8gh5XL15ULdKoXz/cEVHk4utM2T0fDPiy3bMJDCUI1P/fyy8aVY5V9bGagWUEiCiBC9XKUQ5FMa7WbKhi1dVdanNBxXAuy8YKgUurj2Okj23Ahfoz
  template:
    metadata:
      creationTimestamp: null
      name: nats-client-auth
      namespace: default
