apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argo-cd
spec:
  project: observability
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.142.1
    helm:
      values: |-
        mode: daemonset

        image:
          repository: otel/opentelemetry-collector-contrib

        presets:
          logsCollection:
            enabled: true
            storeCheckpoints: true
          kubernetesAttributes:
            enabled: true

        alternateConfig:
          receivers:
            otlp:
              protocols:
                http:
                  endpoint: ${env:MY_POD_IP}:4318
          exporters:
            otlphttp/loki:
              endpoint: http://loki.observability.svc.cluster.local:3100/otlp
            prometheus:
              endpoint: ${env:MY_POD_IP}:8889
              resource_to_telemetry_conversion:
                enabled: true
          processors:
            memory_limiter:
              check_interval: 5s
              limit_percentage: 80
              spike_limit_percentage: 25
            batch: {}
          extensions:
            health_check:
              endpoint: ${env:MY_POD_IP}:13133
          service:
            extensions:
              - health_check
            pipelines:
              logs:
                receivers: []
                processors:
                  - memory_limiter
                  - batch
                exporters:
                  - otlphttp/loki
              metrics:
                receivers:
                  - otlp
                processors:
                  - memory_limiter
                  - batch
                exporters:
                  - prometheus

        ports:
          otlp:
            enabled: false
          otlp-http:
            enabled: true
            containerPort: 4318
            servicePort: 4318
            hostPort: null
            protocol: TCP
          prometheus:
            enabled: true
            containerPort: 8889
            servicePort: 8889
            protocol: TCP
          jaeger-compact:
            enabled: false
          jaeger-thrift:
            enabled: false
          jaeger-grpc:
            enabled: false
          zipkin:
            enabled: false

        serviceMonitor:
          enabled: true
          metricsEndpoints:
            - port: prometheus

        service:
          enabled: true

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
