---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nats-auth
  namespace: nats
spec:
  encryptedData:
    token: AgDMLDQQDP8PTEffmuj2p9X1sC40hHhUmKV7Al5golblgfclpYXwTr81Ga4LIvatE9TRdIFkp8bFQCKWiDlOqme1sA7JqasL7DA2UcM+ou3Gmu8M1/n5eda+bxok6Xhfh+H/Rtti6/+SWF3vfMfk/CpY2mfN7jdl8l0/g//2LKdJPjjJBkO9JRd+dHVTcYpGGxlj1yN82LEWXBNIAVLH1+gpscDRmEf3Ja8PykH70jsMrML2us0nG6EPBYcOvtC/E/mCPo3/DW8x0SdJuZ4Dmoybw22123/C+LXARBe5W1LUQkUfpsyv2l2fCe0oNMUVQ78rm8mkR8V31Tkmj65pbKtS2Pz/23ZRXIwM3+M9E9mDeN+ycJKWEVWY5EHh+ifF/dNEb03Kph2ginHUoFgytZ5iEPZfDcwrqDMUV2qYZWMiiS84RWx7FoEdMl8kNqJnbbwdEp+UWKmsyjVHAYWc9EYpSWFKeIo4OMr6QX8RvqHyXeQCM8GXmv/JrCFy7Q2MXFk1GHSPjh8jCtsyt1o73KQX6B0Vmvxgglg3Vgtu85AQ4cNrx35BfssgnuM+ZgGgCmQrWyvAFOwu/Dt7wbbQ1QfNttGwqylHdOxR9NCZjE8PM/T5LjflCLWCAXFd4RP9v5S6kiCrXs29hPIbsMENbp6VKZfyUb69xDgrzBmX5CX040QHz4/2ymL0Th9gJ3PS2NMbcWoMbmf5aNx3QAoKAUpQmqTIC2FLCHnbNx6aZxY3JZ2sepoK0bkK/CS8LeAKGB2cpedNYgDR+rnac4SXyze0
  template:
    metadata:
      creationTimestamp: null
      name: nats-auth
      namespace: nats
