apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/manifest.yaml
  - platform/argocd-image-updater.yaml
  - platform/nats-auth-sealedsecret.yaml
  - platform/nats.yaml
  - observability/grafana-dashboards.yaml
  - observability/grafana.yaml
  - observability/kube-prometheus-stack.yaml
  - observability/loki.yaml
  - observability/otel-collector.yaml
  - observability/prometheus-operator-crds.yaml
